# -*- coding: utf-8 -*-
"""bva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qSP9AFNG2au59uVuDMjX5zrUp80dJGJt
"""

def bvc(f):
  #n = len(var)
  id = 1
  for i in range(n):
    
    l = [var[i][0], var[i][0]+1, var[i][1], var[i][1]-1]
    for j in range(4):
      #print(id, end=',')
      f.write(str(id) + ',')
      id += 1
      for k in range(n):
        if k == i:
          #print(l[j], end=',')
          f.write(str(l[j]) + ',')
        else:
          #print(var[k][-1], end=',')
          f.write(str(var[k][-1]) + ',')
      f.write('\n')
      #print()

  #print(id, end=',')
  f.write(str(id) + ',')
  for k in range(n):
    #print(var[k][-1], end=',')
    f.write(str(var[k][-1]) + ',')
  #print()
  f.write('\n')


  
def robustness(f):
  bvc(f)
  id = 4*n + 1 + 1
  
  for i in range(n):
    
    l = [var[i][0]-1, var[i][1]+1]
    for j in range(2):
      #print(id, end=',')
      f.write(str(id) + ',')
      id += 1
      for k in range(n):
        if k == i:
          #print(l[j], end=',')
          f.write(str(l[j]) + ',')
        else:
          #print(var[k][-1], end=',')
          f.write(str(var[k][-1]) + ',')
      #print()
      f.write('\n')


	  

def worstCase(f):
  for i in range(n):
    var[i] += [var[i][0]+1, var[i][1]-1]
  
  #id = 1
  
  s = ['1']*n

  loop = 5**n

  for i in range(1, loop+1):
    #print(i, end=',')
    f.write(str(i) + ',')

    for j in range(n):
      #print(var[j][int(s[j])-1], end=',')
      f.write(str(var[j][int(s[j])-1]) + ',')
    #print()
    f.write('\n')

    if s[-1] == '5':

      for k in range(n):
        if s[k] == '5':
          for p in range(k,n):
            s[p] = '1'
          
          s[k-1] = str(int(s[k-1]) + 1)
          break

    else:
      t = ''
      for k in range(n):
        t += s[k]

      num = int(t) + 1
      x = str(num)
      for k in range(n):
        s[k] = x[k]



		
		
#program execution starts from here		
n = int(input('number of parameters: '))
var = []

for _ in range(n):
  print('\nfor variable ' + str(_+1))
  mini = int(input('minimum value of the variable: '))
  maxi = int(input('maximum value of the variable: '))

  var += [[mini, maxi, (mini+maxi)//2]]

print(var)

#from google.colab import files
import csv

header = ['id', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n','o','p']

file_bvc = 'bvc.csv'
with open(file_bvc, 'w', newline='') as f:
  cw = csv.writer(f)
  cw.writerow(header[:n+1])
  bvc(f)
  f.close() 

#files.download(file_bvc)

file_robust = 'robustness.csv'
with open(file_robust, 'w', newline='') as f:
  cw = csv.writer(f)
  cw.writerow(header[:n+1])
  robustness(f)
  f.close()

#files.download(file_robust)

file_worst = 'worstCase.csv'
with open(file_worst, 'w', newline='') as f:
  cw = csv.writer(f)
  cw.writerow(header[:n+1])
  worstCase(f)
  f.close()

#files.download(file_worst)